### ISSUE TITLE
acerca del frontend-challenge

### ISSUE THREAD

**Issue by daniel-990** [ingenieriasapco/frontend-challenge#6]
Hola como estas,  por a qui te dejo el link en donde esta la pagina colgada 
https://challenge-138b0.firebaseapp.com/#/login

salu2

**Comment by daniel-990** [comment]
Hola Cristian, como estas. 
Cristian?.. que pena con vos.. sera que te lo puedo enviar mas tarde el refactor nuevo? estoy tratando de solucionar unos problemas con las rutas y el google maps

**Comment by khriztianmoreno** [comment]
Claro sin lios

**Comment by daniel-990** [comment]
es que tengo este error no se si me puedas ayudar con eso ?.. 

angular.js:9200 Error: Firebase App named '[DEFAULT]' already exists.
    at Error (native)
    at Z (https://www.gstatic.com/firebasejs/3.4.1/firebase.js:26:331)
    at Object.initializeApp (https://www.gstatic.com/firebasejs/3.4.1/firebase.js:25:29)
    at new RutasController (http://localhost:3000/componentes/rutas/rutas-controller.js:12:13)
    at invoke (http://localhost:3000/lib/angular.js:3653:28)
    at Object.instantiate (http://localhost:3000/lib/angular.js:3665:23)
    at http://localhost:3000/lib/angular.js:6686:28
    at http://localhost:3000/lib/angular-ui-router.js:4081:28
    at nodeLinkFn (http://localhost:3000/lib/angular.js:6140:13)
    at compositeLinkFn (http://localhost:3000/lib/angular.js:5552:15) <div ui-view="" class="ng-scope">

esto me da cuando quiero pasar de vistas me toca recargar la pagina para poder verla bien y sin este error no se que pueda ser.

**Comment by daniel-990** [comment]
Hola Cristian como estas, espero las cosas marchen bien.  te acabe de enviar el nuevo pull request 'danielarangorefactoring' con la url del sitio (https://challenge-138b0.firebaseapp.com/?#/login), a la final no pude con los ng-model del mapa, no se que era lo que tenia mal pero no me queria detectar los input (no me los dibujaba en la vista). tambien uni todos los controllers pero siguiendo el esquema practicado el dia de ayer. quedo atento a cualquier cosa muchas gracias de antemano. 

salu2.
